location = "uksouth"
project_name = "Microsoft Zero to Hero"
name = "zero-to-hero"
azure_devops_org_service_url = "https://dev.azure.com/nicholaschang/"
tenant_id = ""
subscription_id = "14a92e37-f24d-48ee-a857-6e2dcbbadc09"